In [231]:
import pandas as pd
import numpy as np
import psycopg2
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 100)
%matplotlib inline

In [13]:
def pg_load_table(file_path, table_name, dbname, user):
    '''
    This function upload csv to a target table
    '''
    try:
        conn = psycopg2.connect(dbname=dbname, user=user)
        print("Connecting to Database")
        cur = conn.cursor()
        f = open(file_path, "r")
        # Truncate the table first
        cur.execute("Truncate {} Cascade;".format(table_name))
        print("Truncated {}".format(table_name))
        # Load table from the file with header
        cur.copy_expert("copy {} from STDIN CSV HEADER QUOTE '\"'".format(table_name), f)
        cur.execute("commit;")
        print("Loaded data into {}".format(table_name))
        conn.close()
        print("DB connection closed.")

    except Exception as e:
        print("Error: {}".format(str(e)))
        sys.exit(1)

In [46]:
dbname = 'gofin'
user = 'timong'
pg_load_table('./user_transactions.csv', 'transactions', dbname, user)
pg_load_table('./user_label_branch_edit.csv', 'user_label_branch', dbname, user)
# decided to load user_base_part1 only as user_base_part2 is just a duplicate of the first (ref to below cell)
pg_load_table('./user_base_part1.csv', 'user_base', dbname, user)

Connecting to Database
Truncated transactions
Loaded data into transactions
DB connection closed.
Connecting to Database
Truncated user_label_branch
Loaded data into user_label_branch
DB connection closed.
Connecting to Database
Truncated user_base
Loaded data into user_base
DB connection closed.

outstanding: total outstanding amount of credit card usage
credit_limit: credit limit amount that can be used
total_cash_usage: last month total cash usage of customer
total_retail_usage: last month total retail usage of customer
bill: last month customer bill amount
remaining_bill: remaining bill that has not been paid in the last month (assuming that this refers to the remaining amount of > month -2 bills that was not paid in month -1)

number_of_cards: # cards owned by customer
branch_code: branch code of bank
default_flag: 1: default, 0: non_default

total_usage = assume total_cash_usage + total_retail_usage
payment_ratio: payment per bill ratio in the last month (payment made to billing amount in the last month)
payment_ratio_3month: payment per bill ratio in the last 3 month
payment_ratio_6month: payment per bill ratio in the last 6 month
overlimit_percentage: overlimit percentage

In [38]:
user1 = pd.read_csv('./user_base_part1.csv')
user2 = pd.read_csv('./user_base_part2.csv')
transactions = pd.read_csv('./user_transactions.csv')
user_label_branch = pd.read_csv('./user_label_branch_edit.csv')

In [9]:
user1.equals(user2)
# user_base_part1 dataframe is exactly the same as user_base_part2

True

## SQL 1

In [206]:
query_combine = """
select 
    label.user_id, label.number_of_cards, label.branch_code, label.default_flag,
    transactions.outstanding, transactions.credit_limit, transactions.bill, transactions.total_cash_usage, transactions.total_retail_usage, transactions.remaining_bill,
    base.payment_ratio, base.overlimit_percentage, base.payment_ratio_3month, base.payment_ratio_6month, base.deliquency_score, base.years_since_card_issuing, base.total_usage,
    base.remaining_bill_per_number_of_cards, base.remaining_bill_per_limit, base.total_usage_per_limit, base.total_3mo_usage_per_limit, base.total_6mo_usage_per_limit,
    base.utilization_3month, base.utilization_6month
from 
    user_label_branch as label
join
    transactions
on 
    label.user_id = transactions.user_id
join
    user_base as base
on 
    label.user_id = base.user_id
"""
combine = pd.read_sql(query_combine, con = psycopg2.connect(database = dbname, user = user))

In [101]:
combine.head()

,user_id,number_of_cards,branch_code,default_flag,outstanding,credit_limit,bill,total_cash_usage,total_retail_usage,remaining_bill,payment_ratio,overlimit_percentage,payment_ratio_3month,payment_ratio_6month,deliquency_score,years_since_card_issuing,total_usage,remaining_bill_per_number_of_cards,remaining_bill_per_limit,total_usage_per_limit,total_3mo_usage_per_limit,total_6mo_usage_per_limit,utilization_3month,utilization_6month
0,1,2,I,0,36158.0,7000000.0,23437.0,0.0,94.0,26323.0,102.19,0.0,74.78,100.00,0.0,15.416667,94.0,13161.5,0.003760,0.000013,0.011719,0.017810,0.013228,0.021949
1,2,2,A,0,268691.0,10000000.0,254564.0,0.0,1012.0,0.0,0.00,0.0,0.00,0.00,NaN,0.750000,1012.0,0.0,0.000000,0.000101,0.000000,0.000000,0.004232,0.000300
2,3,3,A,0,6769149.0,28000000.0,4159779.0,0.0,0.0,0.0,100.00,0.0,100.00,100.91,NaN,10.750000,0.0,0.0,0.000000,0.000000,0.040518,0.047703,0.249389,0.267853
3,4,4,G,0,3496732.0,21000000.0,111231.0,0.0,2536660.0,581334.0,100.00,0.0,25.01,22.64,0.0,19.750000,2536660.0,145333.5,0.027683,0.120793,0.055971,0.016851,0.101912,0.346635
4,5,2,A,0,9402085.0,10000000.0,6099283.0,0.0,2666558.0,5951865.0,95.99,0.0,97.49,99.84,NaN,1.666667,2666558.0,2975932.5,0.595186,0.266656,0.323027,0.131162,0.707865,0.336571

## SQL 2

In [310]:
query_default_stats = """
with main as (
select 
    label.user_id, label.number_of_cards, label.branch_code, label.default_flag,
    transactions.outstanding, transactions.credit_limit, transactions.bill, transactions.total_cash_usage, transactions.total_retail_usage, transactions.remaining_bill,
    base.payment_ratio, base.overlimit_percentage, base.payment_ratio_3month, base.payment_ratio_6month, base.deliquency_score, base.years_since_card_issuing, base.total_usage,
    base.remaining_bill_per_number_of_cards, base.remaining_bill_per_limit, base.total_usage_per_limit, base.total_3mo_usage_per_limit, base.total_6mo_usage_per_limit,
    base.utilization_3month, base.utilization_6month
from 
    user_label_branch as label
join
    transactions
on 
    label.user_id = transactions.user_id
join
    user_base as base
on 
    label.user_id = base.user_id
)
select
    default_flag,
    branch_code,
    count(user_id) as user_count,
    avg(deliquency_score) as avg_deliquency_score,
    percentile_disc(0.5) within group (order by deliquency_score) as median_deliquency_score,
    avg(number_of_cards) as avg_no_cards,
    percentile_disc(0.5) within group (order by number_of_cards) as median_no_cards,
    avg(years_since_card_issuing) as avg_years_since_card_issuing,
    percentile_disc(0.5) within group (order by years_since_card_issuing) as median_years_since_card_issuing,
    avg(outstanding) as avg_outstanding,
    percentile_disc(0.5) within group (order by outstanding) as median_outstanding,
    avg(credit_limit) as avg_credit_limit,
    percentile_disc(0.5) within group (order by credit_limit) as median_credit_limit,
    avg(bill) as avg_bill,
    percentile_disc(0.5) within group (order by bill) as median_bill,
    avg(remaining_bill) as avg_remaining_bill,
    percentile_disc(0.5) within group (order by remaining_bill) as median_remaining_bill,
    avg(remaining_bill_per_number_of_cards) as avg_remaining_bill_per_card,
    percentile_disc(0.5) within group (order by remaining_bill_per_number_of_cards) as median_remaining_bill_per_number_of_cards,
    avg(remaining_bill_per_limit) as avg_remaining_bill_per_limit,
    percentile_disc(0.5) within group (order by remaining_bill_per_limit) as median_remaining_bill_per_limit,
    avg(total_cash_usage) as avg_total_cash_usage,
    percentile_disc(0.5) within group (order by total_cash_usage) as median_total_cash_usage,
    avg(total_retail_usage) as avg_total_retail_usage,
    percentile_disc(0.5) within group (order by total_retail_usage) as median_total_retail_usage,
    avg(total_usage) as avg_total_usage,
    percentile_disc(0.5) within group (order by total_usage) as median_total_usage,
    avg(total_usage_per_limit) as avg_total_usage_per_limit,
    percentile_disc(0.5) within group (order by total_usage_per_limit) as median_total_usage_per_limit,
    avg(total_3mo_usage_per_limit) as avg_total_3mo_usage_per_limit,
    percentile_disc(0.5) within group (order by total_3mo_usage_per_limit) as median_total_3mo_usage_per_limit,
    avg(total_6mo_usage_per_limit) as avg_total_6mo_usage_per_limit,
    percentile_disc(0.5) within group (order by total_6mo_usage_per_limit) as median_total_6mo_usage_per_limit,
    avg(payment_ratio) as avg_payment_ratio,
    percentile_disc(0.5) within group (order by payment_ratio) as median_payment_ratio,
    avg(payment_ratio_3month) as avg_payment_ratio_3mo,
    percentile_disc(0.5) within group (order by payment_ratio_3month) as median_payment_ratio_3mo,
    avg(payment_ratio_6month) as avg_payment_ratio_6mo,
    percentile_disc(0.5) within group (order by payment_ratio_6month) as median_payment_ratio_6mo,
    avg(overlimit_percentage) as avg_overlimit_percentage,
    percentile_disc(0.5) within group (order by overlimit_percentage) as median_overlimit_percentage,
    avg(utilization_3month) as avg_3mo_utilization,
    percentile_disc(0.5) within group (order by utilization_3month) as median_3mo_utilization,
    avg(utilization_6month) as avg_6mo_utilization,
    percentile_disc(0.5) within group (order by utilization_6month) as median_6mo_utilization
from main
group by 1, 2
order by 2, 1
"""
default_stats = pd.read_sql(query_default_stats, con = psycopg2.connect(database = dbname, user = user))

In [311]:
default_stats

,default_flag,branch_code,user_count,avg_deliquency_score,median_deliquency_score,avg_no_cards,median_no_cards,avg_years_since_card_issuing,median_years_since_card_issuing,avg_outstanding,median_outstanding,avg_credit_limit,median_credit_limit,avg_bill,median_bill,avg_remaining_bill,median_remaining_bill,avg_remaining_bill_per_card,median_remaining_bill_per_number_of_cards,avg_remaining_bill_per_limit,median_remaining_bill_per_limit,avg_total_cash_usage,median_total_cash_usage,avg_total_retail_usage,median_total_retail_usage,avg_total_usage,median_total_usage,avg_total_usage_per_limit,median_total_usage_per_limit,avg_total_3mo_usage_per_limit,median_total_3mo_usage_per_limit,avg_total_6mo_usage_per_limit,median_total_6mo_usage_per_limit,avg_payment_ratio,median_payment_ratio,avg_payment_ratio_3mo,median_payment_ratio_3mo,avg_payment_ratio_6mo,median_payment_ratio_6mo,avg_overlimit_percentage,median_overlimit_percentage,avg_3mo_utilization,median_3mo_utilization,avg_6mo_utilization,median_6mo_utilization
0,0,a,8128,0.001367,0.0,2.554872,2,6.777147,5.670000,1.283469e+07,5483803.0,2.476569e+07,11000000.0,8.769491e+06,3528391.0,8.638075e+06,2891734.0,3.152033e+06,1238865.0,0.434780,0.266000,72641.277436,0.0,2.558361e+06,378409.0,2.631043e+06,427000.0,0.110096,0.034000,0.159711,0.103136,0.185219,0.110000,68.511000,36.60,57.287692,54.50,84.437961,66.7,2.616967,0.00,0.542374,0.523742,0.505832,0.450000
1,1,a,772,0.034974,0.0,2.645078,2,6.816958,5.330000,2.215733e+07,6581960.0,2.856606e+07,13000000.0,1.712175e+07,5527047.0,1.920511e+07,5708855.0,6.421481e+06,2675706.0,0.693971,0.850000,117229.367876,0.0,7.773775e+05,0.0,8.946068e+05,0.0,0.034978,0.000000,0.125440,0.054800,0.221830,0.095200,18.576658,0.00,15.156619,20.10,37.813368,28.9,8.150415,0.00,0.721190,0.868000,0.683543,0.750000
2,0,b,1219,0.001641,0.0,2.437244,2,6.447065,5.580000,8.526206e+06,3410092.0,1.477974e+07,6000000.0,6.103418e+06,2487707.0,5.374368e+06,2076427.0,2.064461e+06,944461.0,0.459491,0.329000,137666.589007,0.0,1.877469e+06,150000.0,2.015266e+06,192000.0,0.129873,0.024300,0.184329,0.122821,0.218698,0.121000,56.582067,25.10,72.359934,52.20,78.116760,66.7,3.222986,0.00,0.562925,0.576000,0.530487,0.512561
3,1,b,132,0.000000,0.0,2.424242,2,6.464015,5.000000,9.706657e+06,3586261.0,1.521970e+07,6000000.0,7.930416e+06,3338474.0,7.824128e+06,3232414.0,2.864681e+06,1477983.0,0.604379,0.747779,129166.666667,0.0,4.758968e+05,0.0,6.050635e+05,0.0,0.030750,0.000000,0.127516,0.057919,0.170329,0.086800,16.732273,0.00,35.322955,25.00,49.792879,33.3,7.446591,0.00,0.623807,0.748000,0.573085,0.537000
4,0,c,307,0.006515,0.0,2.416938,2,6.464255,5.670000,7.250387e+06,3632373.0,1.501954e+07,7000000.0,5.654766e+06,3186854.0,5.281793e+06,2587976.0,2.147930e+06,1172769.0,0.465805,0.294000,33859.934853,0.0,1.164391e+06,272379.0,1.198251e+06,307820.0,0.112982,0.031667,0.181747,0.130000,0.218102,0.151000,64.918241,31.80,64.280912,53.60,68.760391,66.7,2.980261,0.00,0.566108,0.599000,0.528078,0.511440
5,1,c,27,0.000000,0.0,2.296296,2,5.812222,5.250000,8.422023e+06,4027195.0,1.385185e+07,7000000.0,7.070592e+06,3487608.0,6.811747e+06,3682477.0,2.682734e+06,1841239.0,0.689242,1.040000,35185.185185,0.0,8.090296e+05,0.0,8.442147e+05,0.0,0.056509,0.000000,0.143865,0.081300,0.229708,0.146000,17.541481,0.00,56.719630,16.91,86.610370,46.2,8.276296,4.36,0.725468,0.927000,0.651004,0.819000
6,0,d,193,0.005181,0.0,2.466321,2,6.830174,5.670000,8.158524e+06,4645467.0,1.459585e+07,7000000.0,5.954875e+06,2408082.0,6.327167e+06,2739377.0,2.335120e+06,1280569.0,0.466917,0.406000,37046.632124,0.0,9.026852e+05,96000.0,9.397319e+05,100000.0,0.098800,0.009030,0.172793,0.098945,0.237442,0.138000,68.188290,28.80,51.799171,49.70,54.455544,60.8,2.894611,0.00,0.577920,0.640000,0.572731,0.588000
7,1,d,12,3.000000,3.0,2.500000,2,6.553306,4.666667,5.998939e+06,3929654.0,1.458333e+07,5000000.0,5.686584e+06,4179179.0,5.003234e+06,3661225.0,1.699731e+06,1830613.0,0.586711,0.732000,NaN,NaN,2.500417e+05,0.0,2.500417e+05,0.0,0.011335,0.000000,0.061745,0.005950,0.084252,0.043800,28.376667,10.10,24.955833,14.10,38.505833,12.2,1.976667,0.00,0.629502,0.801000,0.676764,0.846000
8,0,e,535,0.013084,0.0,2.437383,2,6.135655,5.250000,8.698120e+06,3858611.0,1.531589e+07,6000000.0,6.541631e+06,3160704.0,6.385659e+06,2888880.0,2.470708e+06,1375386.0,0.540497,0.473000,72971.962617,0.0,1.463266e+06,157200.0,1.536206e+06,212000.0,0.120469,0.025100,0.185696,0.119000,0.224648,0.141000,45.823234,19.50,24.732299,49.10,-79.198710,51.8,5.249065,0.00,0.608457,0.619000,0.565512,0.531000
9,1,e,114,1.728070,0.0,2.385965,2,6.542649,6.000000,1.414213e+07,2063070.0,1.836842e+07,6000000.0,1.038201e+07,2011535.0,1.239350e+07,1557436.0,3.984641e+06,778718.0,0.478849,0.287000,61403.508772,0.0,2.804506e+05,0.0,3.418541e+05,0.0,0.024669,0.000000,0.094704,0.007040,0.208226,0.038300,9.316842,0.00,23.516491,20.70,48.705614,30.7,3.608864,0.00,0.531628,0.404000,0.521024,0.576000
10,0,f,1553,0.001935,0.0,2.470702,2,6.586646,5.750000,9.644462e+06,3572509.0,1.683355e+07,7000000.0,6.133652e+06,2543805.0,6.384182e+06,1770815.0,2.362210e+06,825824.0,0.437460,0.267000,68993.256922,0.0,1.731244e+06,208000.0,1.800237e+06,248000.0,0.128885,0.024900,0.187883,0.127417,0.217712,0.133000,114.231597,43.40,28.710464,55.90,109.718886,66.7,3.073825,0.00,0.562878,0.557540,0.524250,0.489000
11,1,f,144,0.000000,0.0,2.694444,2,6.691903,5.580000,2.209711e+07,5339719.0,2.308333e+07,8000000.0,1.508542e+07,4845923.0,2.013744e+07,5154543.0,6.339170e+06,2377798.0,0.771510,0.971026,150347.222222,0.0,1.518519e+06,0.0,1.668866e+06,0.0,0.030048,0.000000,0.136725,0.093500,0.228372,0.114000,-0.326597,0.00,19.489722,21.60,16.872153,25.4,8.047917,2.89,0.798556,0.934000,0.737184,0.862000
12,0,g,536,0.001866,0.0,2.373134,2,6.062058,5.420000,6.655654e+06,3439701.0,1.398787e+07,6000000.0,4.377028e+06,2156970.0,3.973315e+06,1120823.0,1.498267e+06,487031.0,0.395261,0.129000,30701.716418,0.0,1.690657e+06,373920.0,1.721359e+06,384488.0,0.141053,0.054000,0.203421,0.153715,0.223330,0.155000,67.577052,99.00,212.179907,70.60,198.343955,66.7,2.580802,0.00,0.522593,0.485335,0.495616,0.421000
13,1,g,30,0.000000,0.0,2.833333,3,6.603656,5.670000,1.675818e+07,6522120.0,1.806667e+07,7000000.0,1.454119e+07,6305666.0,1.526482e+07,6361390.0,5.234407e+06,2976937.5,0.842753,0.909000,186666.666667,0.0,1.035014e+06,0.0,1.221681e+06,0.0,0.049467,0.000000,0.199896,0.114000,0.304692,0.127000,23.623000,9.64,27.204667,21.10,46.819333,36.0,11.679667,6.36,0.863436,0.948167,0.778723,0.822170
14,0,h,334,0.003003,0.0,2.392216,2,6.507295,5.580000,7.721575e+06,3298004.0,1.476198e+07,6000000.0,6.097793e+06,2548091.0,6.054229e+06,1836264.0,2.250804e+06,856016.0,0.456134,0.287000,45808.383234,0.0,1.383473e+06,87340.0,1.429281e+06,105000.0,0.106692,0.008670,0.178071,0.121000,0.221791,0.134000,47.506287,24.30,50.694371,50.00,211.128952,66.7,3.193503,0.00,0.576439,0.592000,0.534470,0.500000
15,1,h,33,0.000000,0.0,2.333333,2,6.007182,5.580000,6.600326e+06,3980541.0,1.281818e+07,5000000.0,5.190916e+06,3346949.0,5.480239e+06,3300972.0,2.349247e+06,1650486.0,0.587898,0.655000,30303.030303,0.0,1.661576e+05,0.0,1.964606e+05,0.0,0.017353,0.000000,0.120362,0.078000,0.225618,0.133000,13.295455,0.00,7.876364,22.40,38.751212,29.1,7.380909,2.22,0.641307,0.902000,0.637781,0.790000
16,0,i,889,0.003375,0.0,2.388076,2,6.183646,5.000000,8.225831e+06,3872598.0,1.299888e+07,5000000.0,5.469412e+06,2788118.0,5.946553e+06,2909645.0,2.315871e+06,1294819.0,0.537143,0.537000,38954.799775,0.0,1.455952e+06,151028.0,1.494907e+06,182512.0,0.122806,0.020500,0.191190,0.123000,0.232317,0.128000,49.572913,25.60,-9.334578,50.00,64.296873,62.2,3.829708,0.00,0.653003,0.726000,0.600688,0.605000
17,1,i,102,0.000000,0.0,2.470588,2,5.469304,4.416667,1.442864e+07,5213854.0,1.631373e+07,7000000.0,1.090356e+07,3884657.0,1.273640e+07,4687506.0,4.614816e+06,2081872.0,0.748662,0.923000,57843.137255,0.0,4.086566e+05,0.0,4.664998e+05,0.0,0.036940,0.000000,0.126805,0.065400,0.218363,0.109000,18.702255,0.00,29.433529,18.50,44.420784,28.1,6.802255,0.54,0.758098,0.915000,0.679303,0.794751
18,0,j,377,0.007958,0.0,2.403183,2,7.675767,6.670000,7.245646e+06,4128545.0,1.382759e+07,7000000.0,5.132854e+06,2975039.0,4.664065e+06,2306840.0,1.879326e+06,1000000.0,0.453706,0.330000,47745.358090,0.0,1.331914e+06,98066.0,1.379659e+06,112426.0,0.107233,0.013800,0.182236,0.112000,0.224593,0.134000,49.541777,32.10,-51.512414,53.10,64.616870,66.7,3.021141,0.00,0.581383,0.580000,0.549552,0.520000
19,1,j,33,4.484848,4.0,2.272727,2,7.897980,7.500000,2.378929e+06,667120.0,9.333333e+06,5000000.0,1.763800e+06,284964.0,1.957044e+06,232897.0,9.058974e+05,86788.0,0.287932,0.034688,NaN,NaN,2.555303e+05,0.0,2.949242e+05,0.0,0.055318,0.000000,0.060137,0.000129,0.262712,0.009930,16.061818,0.00,27.553939,14.75,70.197879,18.8,1.298485,0.00,0.359937,0.146000,0.486240,0.159000
20,0,k,158,0.000000,0.0,2.322785,2,4.826354,4.170000,8.457255e+06,3471577.0,1.424684e+07,7000000.0,4.714190e+06,1659766.0,4.906485e+06,827958.0,2.057606e+06,413979.0,0.388488,0.130000,46677.215190,0.0,2.495705e+06,272328.0,2.542382e+06,300000.0,0.155565,0.045500,0.184173,0.132000,0.207218,0.135375,63.983165,99.80,104.107975,62.30,122.869177,68.2,2.427911,0.00,0.516594,0.508000,0.462514,0.371000
21,1,k,17,4.882353,5.0,2.411765,2,5.780412,4.920000,9.153972e+06,4756363.0,1.411765e+07,5000000.0,8.477999e+06,4350295.0,7.729623e+06,3091805.0,3.363808e+06,1545903.0,0.659798,0.935000,0.000000,0.0,4.583505e+05,0.0,4.583505e+05,0.0,0.027350,0.000000,0.124619,0.091400,0.217316,0.166000,22.829412,0.00,33.118824,18.60,44.078824,37.4,3.527647,0.00,0.761455,0.933000,0.700330,0.811000

## SQL 3

In [144]:
# check branch_code variant
query_check_bc = """
select distinct
    branch_code
from user_label_branch
"""
check_branch_code = pd.read_sql(query_check_bc, con = psycopg2.connect(database = dbname, user = user))

In [145]:
check_branch_code

   branch_code
0         None
1            b
2            i
3            j
4            H
5            e
6            J
7            C
8            I
9            k
10           A
11           a
12           D
13           f
14           G
15           B
16           F
17           c
18           K
19           E

There are null values in branch code and there is a mix of upper and lower case.

In [171]:
print("number of null values in branch_code column: " + str(len(user_label_branch[user_label_branch.branch_code.isnull()])))
print("% of rows where branch_code is null: " + str(round(len(user_label_branch[user_label_branch.branch_code.isnull()])/user_label_branch.shape[0]*100, 1)) + '%')

number of null values in branch_code column: 195
% of rows where branch_code is null: 1.2%

In [174]:
# change upper case branch code to lower case
user_label_branch = (
    user_label_branch
    .pipe(lambda x: x.assign(branch_code=x.branch_code.str.lower()))
)

In [173]:
user_label_branch2.branch_code.describe()

count     15450
unique       11
top           a
freq       8705
Name: branch_code, dtype: object

In [178]:
# replace null values with 'a' as it occurs the most often
user_label_branch.loc[user_label_branch[user_label_branch.branch_code.isnull()].index.values, 'branch_code'] = 'a'

In [180]:
# reload user_label_branch into psql
user_label_branch.to_csv('./user_label_branch_edit.csv', index=False)
pg_load_table('./user_label_branch_edit.csv', 'user_label_branch', dbname, user)

Connecting to Database
Truncated user_label_branch
Loaded data into user_label_branch
DB connection closed.

In [197]:
# use 'usage' as a proxy to number of transactions completed. assuming higher the usage, the more the number of transactions completed
# since 6 months usage data is available, I shall provide the top 5 users with the most number of 'transactions' from each 'branch code'
# to get total_usage_6months, I will multiply 'total_6mo_usage_per_limit' with 'credit_limit'
# check 'total_6mo_usage_per_limit' and 'credit_limit' for anomaly
combine[['total_6mo_usage_per_limit', 'credit_limit']].describe()

       total_6mo_usage_per_limit  credit_limit
count               15645.000000  1.564500e+04
mean                    0.202454  2.082010e+07
std                     0.274421  2.955419e+07
min                    -0.569000  3.000000e+06
25%                     0.032600  5.000000e+06
50%                     0.117000  9.000000e+06
75%                     0.285000  2.200000e+07
max                     8.110000  1.000000e+09

In [198]:
# there are negative values for total_6mo_usage_per_limit
print("number of entries where total_6mo_usage_per_limit is negative: " + str(len(combine.query("total_6mo_usage_per_limit < 0"))))

number of entries where total_6mo_usage_per_limit is negative: 17

In [201]:
combine.query("total_6mo_usage_per_limit < 0")[['total_usage_per_limit', 'total_6mo_usage_per_limit']]

       total_usage_per_limit  total_6mo_usage_per_limit
40                  0.000000                  -0.081559
208                 0.010286                  -0.001212
1423                0.000000                  -0.000152
3371                0.090400                  -0.012500
4866                0.005380                  -0.009210
5226                0.007330                  -0.000325
7482                0.063800                  -0.037700
8943                0.000000                  -0.025600
9639                0.000000                  -0.009000
10122               0.000000                  -0.137000
10378               0.017800                  -0.002090
10919               0.009020                  -0.000767
11364               0.337000                  -0.569000
11396               0.000000                  -0.160000
14542               0.012000                  -0.005530
14696               0.007700                  -0.000943
15294               0.104000                  -0.078200

In [202]:
# assuming there cannot be negative values for 'total_6mo_usage_per_limit
# from the above dataframe, we can see that 'total_usage_per_limit' and 'total_6mo_usage_per_limit are similar, other than the negative sign
# to clean the data we shall take the absolute of existing value
user1 = (
    user1
    .pipe(lambda x: x.assign(total_6mo_usage_per_limit=abs(x.total_6mo_usage_per_limit)))
)

In [205]:
# reload user_base into psql
user1.to_csv('./user_base_part1_edit.csv', index=False)
pg_load_table('./user_base_part1_edit.csv', 'user_base', dbname, user)

Connecting to Database
Truncated user_base
Loaded data into user_base
DB connection closed.

In [224]:
query_top5 = """
with main as (
select
    base.user_id,
    base.total_6mo_usage_per_limit * t.credit_limit as total_usage_6month,
    label.branch_code
from user_base as base
join transactions as t
on base.user_id = t.user_id
join user_label_branch as label
on base.user_id = label.user_id
)
select
    branch_code,
    rank,
    user_id,
    total_usage_6month
from
    (select
        user_id,
        total_usage_6month,
        branch_code,
        rank() over (partition by branch_code order by total_usage_6month desc) as rank
    from main
    ) as tmp
where rank <= 5
order by 1, 2
"""
top5 = pd.read_sql(query_top5, con = psycopg2.connect(database = dbname, user = user))

In [225]:
top5

   branch_code  rank  user_id  total_usage_6month
0            a     1     9597        8.570000e+08
1            a     2    13236        4.980000e+08
2            a     3    10550        4.543000e+08
3            a     4    11041        4.541600e+08
4            a     5     4056        4.288000e+08
5            b     1    14061        1.434000e+08
6            b     2     9096        1.245000e+08
7            b     3     1442        7.323522e+07
8            b     4    15208        5.187000e+07
9            b     5     2813        5.083000e+07
10           c     1    11551        2.378500e+07
11           c     2    13651        2.320000e+07
12           c     3    15480        1.922400e+07
13           c     4    10617        1.913500e+07
14           c     5    12337        1.568000e+07
15           d     1     7056        5.185800e+07
16           d     2    12704        2.376000e+07
17           d     3     3356        2.014800e+07
18           d     4      233        1.815032e+07
19           d     5    15102        1.680000e+07
20           e     1    15640        3.250500e+07
21           e     1    13547        3.250500e+07
22           e     3     3663        2.929500e+07
23           e     3    15599        2.929500e+07
24           e     5    10638        2.764800e+07
25           f     1     3591        1.376000e+08
26           f     2     1182        1.364048e+08
27           f     3     3411        1.047550e+08
28           f     4    10127        1.041900e+08
29           f     5    11066        9.796000e+07
30           g     1     1408        9.456487e+07
31           g     2    13331        6.150000e+07
32           g     3     1157        3.738000e+07
33           g     4    13674        2.988900e+07
34           g     5    12760        2.550000e+07
35           h     1     7050        1.005000e+08
36           h     2     4717        4.825000e+07
37           h     3    12515        3.328600e+07
38           h     4     8077        2.737800e+07
39           h     5     4290        2.215500e+07
40           i     1     3677        7.617600e+07
41           i     2    11605        6.616000e+07
42           i     3     8469        6.409200e+07
43           i     4     3346        5.508000e+07
44           i     5    10366        3.701100e+07
45           j     1    15385        2.925000e+07
46           j     2    12301        2.863500e+07
47           j     3    10858        2.789800e+07
48           j     4    10420        2.280000e+07
49           j     5    15016        1.796000e+07
50           k     1    12092        5.071600e+07
51           k     2    10610        3.401000e+07
52           k     3    14907        1.640000e+07
53           k     4    13903        1.284000e+07
54           k     5      271        1.216082e+07

## SQL 4

In [272]:
query_decile = """
with main as (
select
    t.user_id,
    label.default_flag,
    t.outstanding,
    ntile(10) over (order by t.outstanding asc) AS decile
FROM transactions as t
join user_label_branch as label
on t.user_id = label.user_id
),
intermediate as (
select 
    decile,
    count(user_id) as user_count,
    sum(default_flag) as default_count,
    cast(sum(default_flag) as float)/cast(count(user_id) as float) as default_rate,
    min(outstanding) as min_outstanding,
    avg(outstanding) as avg_outstanding,
    max(outstanding) as max_outstanding
from main
group by 1
)
select
    decile,
    user_count,
    default_count,
    default_rate,
    sum(default_rate) over (order by decile) as cumulative_default_rate,
    min_outstanding,
    avg_outstanding,
    max_outstanding
from intermediate
order by 1
"""
decile = pd.read_sql(query_decile, con = psycopg2.connect(database = dbname, user = user))

In [273]:
decile

,decile,user_count,default_count,default_rate,cumulative_default_rate,min_outstanding,avg_outstanding,max_outstanding
0,1,1565,344,0.219808,0.219808,0.0,1.321829e+05,334128.0
1,2,1565,53,0.033866,0.253674,334750.0,7.923163e+05,1334327.0
2,3,1565,48,0.030671,0.284345,1334725.0,1.985958e+06,2587708.0
3,4,1565,97,0.061981,0.346326,2587715.0,3.058284e+06,3463385.0
4,5,1565,101,0.064537,0.410863,3463542.0,4.042975e+06,4721563.0
5,6,1564,138,0.088235,0.499098,4722525.0,5.346846e+06,6028571.0
6,7,1564,113,0.072251,0.571349,6029687.0,7.188113e+06,8494395.0
7,8,1564,132,0.084399,0.655748,8496119.0,1.099222e+07,14730155.0
8,9,1564,153,0.097826,0.753574,14730155.0,2.000410e+07,27377448.0
9,10,1564,237,0.151535,0.905108,27377448.0,6.254995e+07,798058574.0